import { defineConfig, externalizeDepsPlugin } from 'electron-vite';
import react from '@vitejs/plugin-react';
import path from 'node:path';
import fs from 'node:fs';
import yaml from 'js-yaml';

const desktopUiSrc = path.resolve(__dirname, '../ui/src');
const bundledWorkspaceDeps = ['@orison/shared-contracts', '@orison/model-protocols', '@orison/story-sync', '@orison/desktop-agent'];

const themesDir = path.resolve(desktopUiSrc, 'shared/themes');
const tokensOut = path.resolve(desktopUiSrc, 'shared/styles/tokens.css');

function buildTokensCss() {
  const staticTokens = `
  --font-ui: "Inter", "Noto Sans SC", "Segoe UI", sans-serif;
  --font-display: "Newsreader", "Noto Serif SC", "Georgia", serif;
  --inspector-width: 300px;
`;
  const files = fs.readdirSync(themesDir).filter((f) => f.endsWith('.yaml'));
  const themes: { name: string; vars: string }[] = [];
  for (const file of files) {
    const name = path.basename(file, '.yaml');
    const obj = yaml.load(fs.readFileSync(path.join(themesDir, file), 'utf-8')) as Record<string, string>;
    const vars = Object.entries(obj).map(([k, v]) => `  --${k}: ${v};`).join('\n');
    themes.push({ name, vars });
  }
  const light = themes.find((t) => t.name === 'light');
  if (!light) return;
  let css = `/* Auto-generated by buildThemes — DO NOT EDIT */\n\n`;
  css += `:root {\n  color-scheme: light;\n${light.vars}\n${staticTokens}}\n\n`;
  for (const theme of themes) {
    const scheme = theme.name === 'dark' ? 'dark' : 'light';
    css += `[data-theme="${theme.name}"] {\n  color-scheme: ${scheme};\n${theme.vars}\n}\n\n`;
  }
  const dark = themes.find((t) => t.name === 'dark');
  if (dark) {
    css += `@media (prefers-color-scheme: dark) {\n  [data-theme="system"] {\n    color-scheme: dark;\n${dark.vars}\n  }\n}\n`;
  }
  css += `\n* {\n  box-sizing: border-box;\n}\n\nhtml,\nbody,\n#root {\n  margin: 0;\n  min-height: 100%;\n}\n\nbody {\n  background: var(--background);\n  color: var(--on-surface);\n  font-family: var(--font-ui);\n}\n`;
  fs.writeFileSync(tokensOut, css, 'utf-8');
}

function themeHotPlugin() {
  return {
    name: 'orison-theme-hot',
    buildStart() { buildTokensCss(); },
    configureServer(server: { watcher: { add(p: string): void; on(e: string, cb: (f: string) => void): void } }) {
      server.watcher.add(themesDir);
      server.watcher.on('change', (file) => {
        if (file.startsWith(themesDir) && file.endsWith('.yaml')) {
          buildTokensCss();
        }
      });
    },
  };
}

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin({ exclude: bundledWorkspaceDeps })],
    build: {
      outDir: 'dist/main',
      lib: {
        entry: path.resolve(__dirname, 'main/index.ts'),
        formats: ['cjs']
      },
      rollupOptions: {
        output: {
          entryFileNames: '[name].cjs'
        }
      }
    }
  },
  preload: {
    plugins: [externalizeDepsPlugin({ exclude: bundledWorkspaceDeps })],
    build: {
      outDir: 'dist/preload',
      lib: {
        entry: path.resolve(__dirname, 'preload/index.ts'),
        formats: ['cjs']
      },
      rollupOptions: {
        output: {
          entryFileNames: '[name].cjs'
        }
      }
    }
  },
  renderer: {
    root: path.resolve(__dirname, 'renderer'),
    plugins: [react(), themeHotPlugin()],
    build: {
      outDir: path.resolve(__dirname, 'dist/renderer'),
      rollupOptions: {
        input: path.resolve(__dirname, 'renderer/index.html')
      }
    },
    resolve: {
      alias: {
        '@desktop-ui': desktopUiSrc
      }
    }
  }
});
