/**
 * buildThemes.ts — 扫描 themes/*.yaml，生成 tokens.css
 * 用法：npx tsx src/shared/themes/buildThemes.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const themesDir = path.resolve(__dirname);
const outFile = path.resolve(__dirname, '../styles/tokens.css');

const staticTokens = `
  --font-ui: "Inter", "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;
  --font-display: "Newsreader", "Georgia", serif;
  --sidebar-width: 260px;
  --inspector-width: 300px;
`;

function yamlToVars(obj: Record<string, string>): string {
  return Object.entries(obj)
    .map(([key, val]) => `  --${key}: ${val};`)
    .join('\n');
}

// 扫描所有 yaml 文件
const files = fs.readdirSync(themesDir).filter((f) => f.endsWith('.yaml'));
const themes: { name: string; vars: string }[] = [];

for (const file of files) {
  const name = path.basename(file, '.yaml');
  const content = fs.readFileSync(path.join(themesDir, file), 'utf-8');
  const obj = yaml.load(content) as Record<string, string>;
  themes.push({ name, vars: yamlToVars(obj) });
}

// light 作为 :root 默认
const light = themes.find((t) => t.name === 'light');
if (!light) {
  console.error('Error: light.yaml is required as the base theme');
  process.exit(1);
}

let css = `/* Auto-generated by buildThemes.ts — DO NOT EDIT */\n\n`;

// :root 使用 light 主题 + 静态 token
css += `:root {\n  color-scheme: light;\n${light.vars}\n${staticTokens}}\n\n`;

// 每个主题生成 [data-theme] 选择器
for (const theme of themes) {
  const scheme = theme.name === 'dark' ? 'dark' : 'light';
  css += `[data-theme="${theme.name}"] {\n  color-scheme: ${scheme};\n${theme.vars}\n}\n\n`;
}

// system 主题：跟随 prefers-color-scheme
const dark = themes.find((t) => t.name === 'dark');
if (dark) {
  css += `@media (prefers-color-scheme: dark) {\n  [data-theme="system"] {\n    color-scheme: dark;\n${dark.vars}\n  }\n}\n`;
}

// 通用 reset
css += `\n* {\n  box-sizing: border-box;\n}\n\nhtml,\nbody,\n#root {\n  margin: 0;\n  min-height: 100%;\n}\n\nbody {\n  background: var(--background);\n  color: var(--on-surface);\n  font-family: var(--font-ui);\n}\n`;

fs.writeFileSync(outFile, css, 'utf-8');
console.log(`Generated ${outFile} with ${themes.length} theme(s): ${themes.map((t) => t.name).join(', ')}`);
